services:
  #Database
  sunrise_db:
    image: mariadb:11.3.2
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 3328:3306
    restart: always
    env_file: .env
    environment:
      MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
      MARIADB_DATABASE: wordpress
    container_name: sunrise_db
  #Web
  sunrise_wp:
    depends_on:
      - sunrise_db
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - 8091:80
    restart: always
    env_file: .env
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_HOST: sunrise_db
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_TABLE_PREFIX: wp_
    container_name: sunrise_wp
    volumes:
      - ./wp-content:/var/www/html/wp-content
  #PhpMyAdmin
  sunrise_myadmin:
    image: phpmyadmin:latest
    container_name: sunrise_myadmin
    restart: "no"
    ports:
      - 5011:80
    environment:
      PMA_HOST: sunrise_db
      UPLOAD_LIMIT: 100M
    depends_on:
      - sunrise_db
volumes:
  db_data:
  wp-content:
